name: Java CI
on: push
jobs:
  CloneDown:
    name: Clone Down Repo
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    needs: CloneDown
    container: gradle:6-jdk11
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build App
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
